[versions]
agp = "8.13.2"
assertj-core = "3.22.0"
coroutines = "1.6.4"
fragmentKtx = "1.6.2"
junit-jupiter = "5.8.2"
kotlin = "2.0.21"
kotlinLanguage = "1.8"
junit = "4.13.2"
mockk = "1.12.8"
purchases = "9.20.2"
detekt = "1.23.6"
android-junit5-version = "1.8.2.0"
mavenPublish = "0.33.0"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
purchases-bc8 = { module = "com.revenuecat.purchases:purchases", version.ref = "purchases" }
purchases-ui-bc8 = { module = "com.revenuecat.purchases:purchases-ui", version.ref = "purchases" }
purchases-amazon-bc8 = { module = "com.revenuecat.purchases:purchases-store-amazon", version.ref = "purchases" }
purchases-bc7 = { module = "com.revenuecat.purchases:purchases-bc7", version.ref = "purchases" }
purchases-ui-bc7 = { module = "com.revenuecat.purchases:purchases-ui-bc7", version.ref = "purchases" }
purchases-amazon-bc7 = { module = "com.revenuecat.purchases:purchases-store-amazon-bc7", version.ref = "purchases" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[plugins]
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
androidJunit5 = { id = "de.mannodermaus.android-junit5", version.ref = "android-junit5-version" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
